extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

# baseline for no optimization
[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

# test structure In/Out is correct, with no optimization
[runs.hw2p1_s0]
pipeline = [
    "bril2json",
    "python3 tdce.py",
    "brili -p {args}",
]

# test simple optimization
[runs.hw2p1_s1]
pipeline = [
    "bril2json",
    "python3 tdce.py tdce",
    "brili -p {args}",
]

[runs.hw2p1_s2]
pipeline = [
    "bril2json",
    "python3 tdce.py raby",
    "brili -p {args}",
]

[runs.hw2p1_s3]
pipeline = [
    "bril2json",
    "python3 tdce.py tdce+",
    "brili -p {args}",
]
