extract = 'total_dyn_inst: (\d+)'
benchmarks = '../bril/benchmarks/core/*.bril'

# baseline for no optimization
[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

# test if the lvn optimization is correct
[runs.hw2p2_s1]
pipeline = [
    "bril2json",
    "python3 lvn.py",
    "brili -p {args}",
]

# test if the lvn optimization is correct
[runs.hw2p2_s2]
pipeline = [
    "bril2json",
    "python3 lvn.py",
    "python3 tdce.py tdce",
    "brili -p {args}",
]
